replicaCount: 1

image:
  tag: "dev"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

ingress:
  hosts:
    - host: api.dev.data-dashboard.example.com
      paths:
        - path: /
          pathType: Prefix
