replicaCount: 1

image:
  tag: "stage"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  hosts:
    - host: api.stage.data-dashboard.example.com
      paths:
        - path: /
          pathType: Prefix
